---
title: "Potassium bin distribution(among 7 days) plot"
author: "JunmeiW"
date: "2019年5月1日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

-------------------------------------
## Plot potassium bin distribution among 7days
```{r}
##get data
bin7_hist = read.csv("data/bin7_hist.csv")
# bin7_hist$daytime = as.factor(bin7_hist$daytime)
bin7_hist$potassium_bin = as.factor(bin7_hist$potassium_bin)
```

```{r}
library(ggplot2)
library(sqldf)
```


```{r}
table(bin7_hist$daytime)
```


```{r}
bin7_hist$potassium_value[bin7_hist$potassium_bin ==1] <- '4.0~4.5'
bin7_hist$potassium_value[bin7_hist$potassium_bin ==2] <- '3.5~4.0'
bin7_hist$potassium_value[bin7_hist$potassium_bin ==3] <- '3.0~3.5'
bin7_hist$potassium_value[bin7_hist$potassium_bin ==4] <- '<3.0'
```


plot hist
```{r}
pdf("data/update0405/results0409/bin_count.pdf")
ggplot(bin7_hist, aes(x = potassium_bin, fill=potassium_value ))+
  geom_bar(aes(y =(..count../sum(..count..))*100))+
  scale_fill_brewer(palette="Dark2") +
  # geom_text(aes(label=y),
  # vjust=1.6, color="white",
  #           position = position_dodge(0.9),size=3.5) +
  facet_wrap(~daytime)+
  ylab(label = "precent(%)")+
  theme(legend.direction = "horizontal", legend.position = "top")
dev.off()
```


### split data by daytime
```{r}
day1 <- bin7_hist[bin7_hist[,2]==1,]
day2 <- bin7_hist[bin7_hist[,2]==2,]
day3 <- bin7_hist[bin7_hist[,2]==3,]
day4 <- bin7_hist[bin7_hist[,2]==4,]
day5 <- bin7_hist[bin7_hist[,2]==5,]
day6 <- bin7_hist[bin7_hist[,2]==6,]
day7 <- bin7_hist[bin7_hist[,2]==7,]
```


```{r}
day1 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day1
                  group by potassium_bin,potassium_value,daytime
                 ")
day1$percent <- round((day1$bin_count/90379)*100,1)


day2 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day2
                  group by potassium_bin,potassium_value,daytime
                 ")
day2$percent <- round((day2$bin_count/60649)*100,1)


day3 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day3
                  group by potassium_bin,potassium_value,daytime
                 ")
day3$percent <- round((day3$bin_count/32649)*100,1)


day4 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day4
                  group by potassium_bin,potassium_value,daytime
                 ")
day4$percent <- round((day4$bin_count/19069)*100,1)

day5 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day5
                  group by potassium_bin,potassium_value,daytime
                 ")
day5$percent <- round((day5$bin_count/12337)*100,1)

day6 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day6
                  group by potassium_bin,potassium_value,daytime
                 ")
day6$percent <- round((day6$bin_count/8526)*100,1)

day7 <- sqldf("select distinct potassium_bin,
                  potassium_value,daytime,count(*) as bin_count
                  from day7
                  group by potassium_bin,potassium_value,daytime
                 ")
day7$percent <- round((day7$bin_count/6176)*100,1)
```

```{r}
comday <- rbind(day1, day2, day3, day4, day5, day6, day7)
```

```{r}
library(plyr)
# Sort by dose and supp
df_sorted <- arrange(comday, daytime, potassium_bin) 
head(df_sorted)
```

### confirm the label position in the bar plot
```{r}
# Calculate the cumulative sum of percent for each daytime
df_cumsum <- ddply(df_sorted, "daytime",
                   transform, label_ypos=cumsum(percent)- 0.5*percent)
head(df_cumsum)
```



```{r}
pdf("data/update0405/results0409/bin_count_cum.pdf")
ggplot(df_cumsum, aes(x = daytime, y=percent,
                       fill=potassium_value ))+
  geom_bar(stat = "identity", width = 0.8)+
  scale_fill_brewer(palette="Dark2") +
  geom_text(aes(y=label_ypos,label=percent),
  color="black", #position = position_dodge(1.2),
            size=3.3) +
  scale_x_continuous(breaks=seq(1,7,1), labels = c("Day 1","Day 2","Day 3","Day 4",
                                                   "Day 5","Day 6","Day 7"))+
  ylab(label = "Precent(%)")
# + theme(legend.direction = "vertical", legend.position = "right")
dev.off()
```



